### ISSUE TITLE
v1.0.13 not working (SSL issue?).

### ISSUE THREAD

**Issue by ronaldknol** [shirosaidev/diskover#12]
I have been busy and not keeping up with DiskOver, I went from version 1.0.5 to 1.0.13, but it no longer runs.
First I ran into AWS issues - had to ensure aws=False in the cfg file. but then:

```elasticsearch.exceptions.ImproperlyConfigured: Please install requests to use RequestsHttpConnection.```

So I did `pip install requests` and then it went past that, but I ended up with:

```root@linserver03:~/diskover.1013# python diskover.py -d /tmp

    _/_/_/    _/            _/
   _/    _/        _/_/_/  _/  _/      _/_/    _/      _/    _/_/    _/  _/_/
  _/    _/  _/  _/_/      _/_/      _/    _/  _/      _/  _/_/_/_/  _/_/
 _/    _/  _/      _/_/  _/  _/    _/    _/    _/  _/    _/        _/
_/_/_/    _/  _/_/_/    _/    _/    _/_/        _/ v1.0.13  _/_/_/  _/
                              https://github.com/shirosaidev/diskover

2017-05-29 13:35:56,326 [INFO][diskover] Connecting to Elasticsearch
2017-05-29 13:35:56,364 [WARNING][elasticsearch] HEAD https://localhost:9200/ [status:N/A request:0.038s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 75, in perform_request
    timeout=timeout or self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
2017-05-29 13:35:56,374 [WARNING][elasticsearch] HEAD https://localhost:9200/ [status:N/A request:0.009s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 75, in perform_request
    timeout=timeout or self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
2017-05-29 13:35:56,389 [WARNING][elasticsearch] HEAD https://localhost:9200/ [status:N/A request:0.011s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 75, in perform_request
    timeout=timeout or self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
2017-05-29 13:35:56,396 [WARNING][elasticsearch] HEAD https://localhost:9200/ [status:N/A request:0.007s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 75, in perform_request
    timeout=timeout or self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
2017-05-29 13:35:56,396 [ERROR][diskover] Unable to connect to Elasticsearch
```

Please keep the documentation up-to-date; the pip requests install was not met by pip install requirements.
This latest issue seems to be SSL related? ElasticSearch is running.

**Comment by shirosaidev** [comment]
Please reply with your diskover.cfg file.

**Comment by shirosaidev** [comment]
**line 2** in the output looks like it's trying to connect to **https://localhost:9200/**.

Try setting your diskover.cfg to:

> ;aws = False
> port = 9200
> host = localhost
> ;user = elastic
> ;password = changeme

**Comment by shirosaidev** [comment]
This has been fixed in **v1.0.15**.

**Comment by ronaldknol** [comment]
v1.0.15 works for me. Thanks!

**Comment by shirosaidev** [comment]
Happy to hear. Give diskover web a try and let me know what you think. It's a new feature to diskover which I'm hoping will be useful to a lot of studios.
