### ISSUE TITLE
Missing diskover_redis_worker.py

### ISSUE THREAD

**Issue by proadmin** [shirosaidev/diskover#20]
The GIT repository seems to be missing the diskover_redis_worker.py module. 

```
$ python diskover.py -d /home/proadmin
Traceback (most recent call last):
  File "diskover.py", line 24, in <module>
    import diskover_worker_bot
  File "/home/echristensen/diskover/diskover/diskover_worker_bot.py", line 14, in <module>
    import diskover
  File "/home/echristensen/diskover/diskover/diskover.py", line 28, in <module>
    import diskover_dupes
  File "/home/echristensen/diskover/diskover/diskover_dupes.py", line 15, in <module>
    import diskover_redis_worker
ImportError: No module named diskover_redis_worker
```

**Comment by shirosaidev** [comment]
This has been fixed in the newest release, diskover_redis_worker.py has been renamed to diskover_worker_bot.py.
