### ISSUE TITLE
redis.exceptions.ConnectionError: Error 104 while writing to socket. Connection reset by peer.

### ISSUE THREAD

**Issue by ravitejamandapati** [shirosaidev/diskover#22]
Hello,

When i run the scan on some larger filesystem. the script was terminating with below below error. Can you please check it once. Let me know if i need to tune something from redis side to accept larger datasets.

Environment : 
python 3.6
Redhat Ent Linux 7.2
redis 4.0.9
elasticsearch 5.6.9

Error:
/crawler_pybin/python/bin/python /crawler_pybin/diskover/diskover.py -d /proj/diablo -i diskover-xhd-proj-diablo -a

   ___       ___       ___       ___       ___       ___       ___       ___
  /\  \     /\  \     /\  \     /\__\     /\  \     /\__\     /\  \     /\  \
/::\  \   _\:\  \   /::\  \   /:/ _/_   /::\  \   /:/ _/_   /::\  \   /::\  \
/:/\:\__\ /\/::\__\ /\:\:\__\ /::-"\__\ /:/\:\__\ |::L/\__\ /::\:\__\ /::\:\__\
\:\/:/  / \::/\/__/ \:\:\/__/ \;:;-",-" \:\/:/  / |::::/  / \:\:\/  / \;:::/  /
\::/  /   \:\__\    \::/  /   |:|  |    \::/  /   L;;/__/   \:\/  /   |:\/__/
  \/__/     \/__/     \/__/     \|__|     \/__/               \/__/     \|__|
                                      v1.5.0-rc1
                                      https://shirosaidev.github.io/diskover
                                      Bringing light to the darkness.
                                      Support diskover on Patreon or PayPal :)

    
2018-04-25 08:05:49,472 [INFO][diskover] Checking es index: diskover-xhd-proj-diablo
2018-04-25 08:05:49,475 [INFO][diskover] Creating es index
2018-04-25 08:05:50,105 [INFO][diskover] Adding disk space info to es index
2018-04-25 08:05:50,152 [INFO][diskover] Found 60 diskover RQ worker bots
2018-04-25 08:05:50,152 [INFO][diskover] Enqueueing crawl to diskover worker bots for /proj/diablo...
2018-04-25 08:05:50,152 [INFO][diskover] Sending adaptive batches to worker bots
Crawling: [===================================================================================================================================================================================] 100% (Elapsed Time: 6:37:53, Time:  6:37:53)
2018-04-25 14:43:44,019 [INFO][diskover] Finished crawling!
2018-04-25 14:43:44,020 [INFO][diskover] Waiting for diskover bots to be done with any crawl jobs...
2018-04-25 14:43:45,102 [INFO][diskover] Getting diskover bots to calculate directory sizes...
2018-04-25 14:43:45,102 [INFO][diskover] Searching for all directory docs in diskover-xhd-proj-diablo
2018-04-25 14:50:26,777 [INFO][diskover] Found 10011451 directory docs
Traceback (most recent call last):
  File "/crawler_pybin/python/lib/python3.6/site-packages/redis/connection.py", line 590, in send_packed_command
    self._sock.sendall(item)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/crawler_pybin/python/lib/python3.6/site-packages/redis/client.py", line 2879, in execute
    return execute(conn, stack, raise_on_error)
  File "/crawler_pybin/python/lib/python3.6/site-packages/redis/client.py", line 2749, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "/crawler_pybin/python/lib/python3.6/site-packages/redis/connection.py", line 603, in send_packed_command
    (errno, errmsg))
redis.exceptions.ConnectionError: Error 104 while writing to socket. Connection reset by peer.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/crawler_pybin/python/lib/python3.6/site-packages/redis/connection.py", line 590, in send_packed_command
    self._sock.sendall(item)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/crawler_pybin/diskover/diskover.py", line 1408, in <module>
    calc_dir_sizes(addstats=True)
  File "/crawler_pybin/diskover/diskover.py", line 1105, in calc_dir_sizes
    args=(dirbatch, cliargs,))
  File "/crawler_pybin/python/lib/python3.6/site-packages/rq/queue.py", line 300, in enqueue
    job_id=job_id, at_front=at_front, meta=meta)
  File "/crawler_pybin/python/lib/python3.6/site-packages/rq/queue.py", line 252, in enqueue_call
    job = self.enqueue_job(job, at_front=at_front)
  File "/crawler_pybin/python/lib/python3.6/site-packages/rq/queue.py", line 325, in enqueue_job
    pipe.execute()
  File "/crawler_pybin/python/lib/python3.6/site-packages/redis/client.py", line 2894, in execute
    return execute(conn, stack, raise_on_error)
  File "/crawler_pybin/python/lib/python3.6/site-packages/redis/client.py", line 2749, in _execute_transaction
    connection.send_packed_command(all_cmds)
  File "/crawler_pybin/python/lib/python3.6/site-packages/redis/connection.py", line 603, in send_packed_command
    (errno, errmsg))
redis.exceptions.ConnectionError: Error 104 while writing to socket. Connection reset by peer.

**Comment by shirosaidev** [comment]
Try with rc3 and let me know if you still get this error.

**Comment by ravitejamandapati** [comment]
May i know the reason for above error. That will helps me in future.

**Comment by shirosaidev** [comment]
did you try rc3? no more error?

**Comment by shirosaidev** [comment]
rc3 has fixes to hopefully make this error go away, before rc3 directory batch size could get too large using -a so I set maxsize of batch size to limit data added to Redis.

**Comment by ravitejamandapati** [comment]
Thank you. Let me try with rc3 and let you know the status.

**Comment by ravitejamandapati** [comment]
With rc3 scan was completed successfully. Thank you.

**Comment by abhimanyu3** [comment]
rc3 ??? you mean  redis server...I am having that but still getting the issue

Redis server v=3.2.0 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64

**Comment by shirosaidev** [comment]
What version of diskover are you running? Are you cacheing dir times in redis (diskover.cfg setting)?

**Comment by shirosaidev** [comment]
Try updating to redis 4.0.9 and crawl with diskover 1.5.0-rc17.

**Comment by ravitejamandapati** [comment]
i'm rebuilding complete thing from scratch. give me some time. i will re-initiate with new rc17 and share you the result.

**Comment by ravitejamandapati** [comment]
Do we have any option to perform one time incremental scan once a day. instead of continues scan.

**Comment by shirosaidev** [comment]
there is currently no incremental indexing, usually people just create a new index daily or weekly using a different name and then can compare data between two indices to see change using diskover-web.

**Comment by shirosaidev** [comment]
please try latest rc21 and see if you get these issues with redis, there is a new setting in diskover.cfg.sample for redis "ttl" which you could try setting to lower value than default 500 to store keys/results in redis. You could also set maxmemory and memory policy in redis conf to evict keys which are no longer needed by diskover.
