### ISSUE TITLE
Followed guide but Cannot launch python diskover_worker_bot.py

### ISSUE THREAD

**Issue by yasnick** [shirosaidev/diskover#29]
administrator@search-engine:~/diskover$ python diskover_worker_bot.py

     ___  _ ____ _  _ ____ _  _ ____ ____     ;
     |__> | ==== |-:_ [__]  \/  |=== |--<    ["]
     ____ ____ ____ _  _ _    ___  ____ ___ /[_]\
     |___ |--< |--| |/\| |___ |==] [__]  |   ] [ v1.5.0-rc10

     Redis RQ worker bot for diskover crawler
     Crawling all your stuff.

    
Traceback (most recent call last):
  File "diskover_worker_bot.py", line 1198, in <module>
    w.work()
  File "/home/administrator/.local/lib/python2.7/site-packages/rq/worker.py", line 466, in work
    self.register_birth()
  File "/home/administrator/.local/lib/python2.7/site-packages/rq/worker.py", line 273, in register_birth
    if self.connection.exists(self.key) and \
  File "/home/administrator/.local/lib/python2.7/site-packages/redis/client.py", line 951, in exists
    return self.execute_command('EXISTS', name)
  File "/home/administrator/.local/lib/python2.7/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/home/administrator/.local/lib/python2.7/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/administrator/.local/lib/python2.7/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/home/administrator/.local/lib/python2.7/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.

**Comment by shirosaidev** [comment]
is redis server running on localhost? Looks like the workerbot can't communicate with redis server.

**Comment by shirosaidev** [comment]
redis server needs to be installed, see https://redis.io/ . If you are using Ubuntu or CentOS you should be able to install with apt or yum.

**Comment by shirosaidev** [comment]
pip just installs the redis python modules needed to communicate with redis server.
