### ISSUE TITLE
Index names case not handled

### ISSUE THREAD

**Issue by helge000** [shirosaidev/diskover#30]
Specifying an index with upper case letters is not supported in elasticsearch and raises an unhandled exception. There should be a simple regex check for the index name, IMHO we should just `lower()` it:

```bash
# ./diskover.py -i diskover-TEST -a 
2018-08-15 15:04:09,817 [INFO][diskover] Checking es index: diskover-TEST
2018-08-15 15:04:09,825 [INFO][diskover] Creating es index
2018-08-15 15:04:09,829 [WARNING][elasticsearch] PUT http://localhost:9200/diskover-TEST [status:400 request:0.003s]
Traceback (most recent call last):
  File "./diskover.py", line 1847, in <module>
    index_create(cliargs['index'])
  File "./diskover.py", line 667, in index_create
    es.indices.create(index=indexname, body=mappings)
  File "/usr/lib/python2.7/site-packages/elasticsearch5/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch5/client/indices.py", line 107, in create
    params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch5/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch5/connection/http_urllib3.py", line 129, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch5/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch5.exceptions.RequestError: TransportError(400, u'invalid_index_name_exception', u'Invalid index name [diskover-TEST], must be lowercase') 
```

**Comment by helge000** [comment]
I can send a PR, simple enough, and would maybe start [here](https://github.com/shirosaidev/diskover/blob/master/diskover.py#L1658). However, this seems to be a litte messy, should we rather use Regex here?

**Comment by shirosaidev** [comment]
Send a PR with the code changes you are thinking. There are 3 types of index name requirements based on what cli args are used, qumulo storage, s3 storage and regular index you can see that on lines 1658-1688.
