### ISSUE TITLE
failed to index because elastiscsearch's long is to small

### ISSUE THREAD

**Issue by mathse** [shirosaidev/diskover#37]
hi,

I have a Netapp serving data via cifs - some of my files have inodes like this
18091310060841039723
and the upper limit of 'long' is
9223372036854775807

so I would recommend to change this to something which fit better

here is my traceback 

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/rq/worker.py", line 793, in perform_job
    rv = job.perform()
  File "/usr/lib/python3.6/site-packages/rq/job.py", line 599, in perform
    self._result = self._execute()
  File "/usr/lib/python3.6/site-packages/rq/job.py", line 605, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/app/diskover/diskover_bot_module.py", line 926, in scrape_tree_meta
    es_bulk_add(worker, tree_dirs, tree_files, cliargs, totalcrawltime)
  File "/app/diskover/diskover_bot_module.py", line 756, in es_bulk_add
    index_bulk_add(es, docs, config, cliargs)
  File "/app/diskover/diskover.py", line 674, in index_bulk_add
    request_timeout=config['es_timeout'])
  File "/usr/lib/python3.6/site-packages/elasticsearch5/helpers/__init__.py", line 257, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/usr/lib/python3.6/site-packages/elasticsearch5/helpers/__init__.py", line 192, in streaming_bulk
    raise_on_error, **kwargs)
  File "/usr/lib/python3.6/site-packages/elasticsearch5/helpers/__init__.py", line 137, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
elasticsearch5.helpers.BulkIndexError: ('219 document(s) failed to index.', [{'index': {'_index': 'diskover-2018-11-09', '_type': 'directory', '_id': 'AWb5FhNAnxb8tCnaFPa3', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': 'failed to parse [inode]', 'caused_by': {'type': 'json_parse_exception', 'reason': 'Numeric value (18091310060841039723) out of range of long (-9223372036854775808 - 9223372036854775807)\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@4586eede; line: 1, column: 330]'}}, ...

**Comment by shirosaidev** [comment]
what cifs mount options are you using? Are you setting any of "nounix" or "noserverino" or "serverino" ? What is output of mount command?

**Comment by mathse** [comment]
There will be no problem with the crawler when I mount it with 'noserverino' but I assume that one file will have different inodes between 2 mounts, right?

- -

Sent from Nine
________________________________

**Comment by shirosaidev** [comment]
This has been fixed in v1.5.0-rc25, long has been changed to double number type for inode fields es mapping for file and directory docs.
