### ISSUE TITLE
Diskover v1.5.0-rc25 failed to create index

### ISSUE THREAD

**Issue by salus-sage** [shirosaidev/diskover#42]
Hi, I followed the installation instructions and ran the below command which returned an eeror, logs attached.
Your help will be much appreciated, thanks.

`python /path/to/diskover.py -d /rootpath/you/want/to/crawl -i diskover-indexname -a -O`

``` 2018-12-19 20:39:35,017 [INFO][diskover] Using config file: /home/salussage/diskover/diskover.cfg
2018-12-19 20:39:35,017 [WARNING][diskover] Not running as root, permissions might block crawling some files
2018-12-19 20:39:35,017 [INFO][diskover] Checking es index: diskover-index
2018-12-19 20:39:35,019 [INFO][diskover] Creating es index
2018-12-19 20:39:35,059 [WARNING][elasticsearch] PUT http://localhost:9200/diskover-index [status:400 request:0.039s]
Traceback (most recent call last):
  File "diskover.py", line 2100, in <module>
    pre_crawl_tasks()
  File "diskover.py", line 1822, in pre_crawl_tasks
    index_create(cliargs['index'])
  File "diskover.py", line 698, in index_create
    es.indices.create(index=indexname, body=mappings)
  File "/home/salussage/diskover/local/lib/python2.7/site-packages/elasticsearch5/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/salussage/diskover/local/lib/python2.7/site-packages/elasticsearch5/client/indices.py", line 107, in create
    params=params, body=body)
  File "/home/salussage/diskover/local/lib/python2.7/site-packages/elasticsearch5/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/salussage/diskover/local/lib/python2.7/site-packages/elasticsearch5/connection/http_urllib3.py", line 129, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/salussage/diskover/local/lib/python2.7/site-packages/elasticsearch5/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch5.exceptions.RequestError

 ```

**Comment by shirosaidev** [comment]
Are you running elasticsearch 5.6.x on same host as diskover.py ? If so, what is the output of
`curl -XGET "http://localhost:9200"`
If you are running on different host, you need to set es host in diskover.cfg.

**Comment by shirosaidev** [comment]
that looks like an older version of es (1.7.2), diskover requires elasticsearch 5.6.x.

**Comment by salus-sage** [comment]
Thanks, That resolved my issue, i will close this.
