### ISSUE TITLE
OS/IO Exception caused by: [Errno 2] No such file or directory ... caused by whitespace at the end

### ISSUE THREAD

**Issue by mathse** [shirosaidev/diskover#46]
Folders with whitespaces at the end throughs "OS/IO Exception caused by: [Errno 2] No such file or directory" even though the path is fully readable

diskover shows the path as:
u'/mnt/mountpoint/Endoderm /Some_content' (whitespace at the end of 'Endoderm')

bash:
ls -l /mnt/mountpoint/Endoderm\ /
drwxr-xr-x. 2 root root 0 Aug 23 22:30 Some_content

**Comment by shirosaidev** [comment]
I tested some directories with white spaces and am not seeing any io/os errors with python 3.6.5 and scandir 1.9.0. All the directories with spaces get indexed...

**Comment by shirosaidev** [comment]
`pip3 install scandir`

**Comment by mathse** [comment]
Traceback (most recent call last):
  File "diskover_worker_bot.py", line 61, in <module>
    main()
  File "diskover_worker_bot.py", line 35, in main
    w.work(logging_level=cliargs_bot['loglevel'])
  File "/usr/lib/python3.6/site-packages/rq/worker.py", line 494, in work
    self.execute_job(job, queue)
  File "/usr/lib/python3.6/site-packages/rq/worker.py", line 918, in execute_job
    return self.perform_job(job, queue, heartbeat_ttl=timeout)
  File "/usr/lib/python3.6/site-packages/rq/worker.py", line 787, in perform_job
    self.prepare_job_execution(job, heartbeat_ttl)
  File "/usr/lib/python3.6/site-packages/rq/worker.py", line 712, in prepare_job_execution
    registry.add(job, timeout, pipeline=pipeline)
  File "/usr/lib/python3.6/site-packages/rq/registry.py", line 47, in add
    return pipeline.zadd(self.key, {job.id: score})
  File "/usr/lib/python3.6/site-packages/redis/client.py", line 2315, in zadd
    raise RedisError("ZADD requires an equal number of "
redis.exceptions.RedisError: ZADD requires an equal number of values and scores

**Comment by shirosaidev** [comment]
Please try the latest rc27 code and let me know if this is still an issue.

**Comment by shirosaidev** [comment]
check also you are running the exact versions that are in requirements.txt for python modules rq and redis, newer versions don't work with diskover.

**Comment by mathse** [comment]
yep now works with python 3.6

**Comment by mathse** [comment]
need to reopen this since its not solved yet in python 3.6.7
