### ISSUE TITLE
BotError: Moving job to u'failed' queue

### ISSUE THREAD

**Issue by mathse** [shirosaidev/diskover#47]
I have problems scanning a big nfs share - some bots giving me those errors

22:30:25 TransportError: TransportError(429, u'es_rejected_execution_exception', u'rejected execution of org.elasticsearch.transport.TransportService$7@5392962b on EsThreadPoolExecutor[bulk, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@431b1929[Running, pool size = 4, active threads = 4, queued tasks = 200, completed tasks = 446339]]')
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rq/worker.py", line 793, in perform_job
    rv = job.perform()
  File "/usr/lib/python2.7/site-packages/rq/job.py", line 599, in perform
    self._result = self._execute()
  File "/usr/lib/python2.7/site-packages/rq/job.py", line 605, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/opt/mdc/bin/diskover/diskover_bot_module.py", line 1003, in scrape_tree_meta
    es_bulk_add(worker, tree_dirs, tree_files, cliargs, totalcrawltime)
  File "/opt/mdc/bin/diskover/diskover_bot_module.py", line 865, in es_bulk_add
    es.index(index=cliargs['index'], doc_type='worker', body=data)
  File "/usr/lib/python2.7/site-packages/elasticsearch5/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch5/client/__init__.py", line 300, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch5/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch5/connection/http_urllib3.py", line 129, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch5/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
TransportError: TransportError(429, u'es_rejected_execution_exception', u'rejected execution of org.elasticsearch.transport.TransportService$7@5392962b on EsThreadPoolExecutor[bulk, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@431b1929[Running, pool size = 4, active threads = 4, queued tasks = 200, completed tasks = 446339]]')
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rq/worker.py", line 793, in perform_job
    rv = job.perform()
  File "/usr/lib/python2.7/site-packages/rq/job.py", line 599, in perform
    self._result = self._execute()
  File "/usr/lib/python2.7/site-packages/rq/job.py", line 605, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/opt/mdc/bin/diskover/diskover_bot_module.py", line 1003, in scrape_tree_meta
    es_bulk_add(worker, tree_dirs, tree_files, cliargs, totalcrawltime)
  File "/opt/mdc/bin/diskover/diskover_bot_module.py", line 865, in es_bulk_add
    es.index(index=cliargs['index'], doc_type='worker', body=data)
  File "/usr/lib/python2.7/site-packages/elasticsearch5/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch5/client/__init__.py", line 300, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch5/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch5/connection/http_urllib3.py", line 129, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch5/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
TransportError: TransportError(429, u'es_rejected_execution_exception', u'rejected execution of org.elasticsearch.transport.TransportService$7@5392962b on EsThreadPoolExecutor[bulk, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@431b1929[Running, pool size = 4, active threads = 4, queued tasks = 200, completed tasks = 446339]]')
22:30:25 Moving job to u'failed' queue

**Comment by shirosaidev** [comment]
There was a bug in the previous rc27 dir calcs code, the latest up on github should fix this issue, please reply with your results.

**Comment by mathse** [comment]
looks better - but now got this problem

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/redis/client.py", line 2772, in _execute_transaction
    response = self.parse_response(connection, '_')
  File "/usr/lib/python3.6/site-packages/redis/client.py", line 2838, in parse_response
    self, connection, command_name, **options)
  File "/usr/lib/python3.6/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/usr/lib/python3.6/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ExecAbortError: Transaction discarded because of previous errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mdc/bin/diskover/diskover_worker_bot.py", line 49, in <module>
    w.work(logging_level=cliargs_bot['loglevel'])
  File "/usr/lib/python3.6/site-packages/rq/worker.py", line 466, in work
    self.register_birth()
  File "/usr/lib/python3.6/site-packages/rq/worker.py", line 289, in register_birth
    p.execute()
  File "/usr/lib/python3.6/site-packages/redis/client.py", line 2879, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/lib/python3.6/site-packages/redis/client.py", line 2777, in _execute_transaction
    raise errors[0][1]
  File "/usr/lib/python3.6/site-packages/redis/client.py", line 2764, in _execute_transaction
    self.parse_response(connection, '_')
  File "/usr/lib/python3.6/site-packages/redis/client.py", line 2838, in parse_response
    self, connection, command_name, **options)
  File "/usr/lib/python3.6/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/usr/lib/python3.6/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: Command # 1 (DEL rq:worker:sl-it-p-crwlr1.14951) of pipeline caused error: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

**Comment by mathse** [comment]
and those errors

`22:30:25 TransportError: TransportError(429, u'es_rejected_execution_exception', u'rejected execution of org.elasticsearch.transport.TransportService$7@5392962b on EsThreadPoolExecutor[bulk, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@431b1929[Running, pool size = 4, active threads = 4, queued tasks = 200, completed tasks = 446339]]')`

are still all over the place
I think this has something to do with elasticsearch

i found this thread 
https://discuss.elastic.co/t/elasticsearch-problem-search-thread-pool-rejected/114446/3
which didn't solved the problem for me

**Comment by shirosaidev** [comment]
in latest rc27 each bot starts up 4 threads to do dir calcs but I think that is causing those issues with ES you are seeing above, you are starting 128 workers so this might be the issue, try starting 32 workers and see if it goes away. Redis errors you might want to look at the storage that rdb snapshots are configured to save to, is there enough free space, is it writable by the user running redis server? You could try to kill all workers, empty rq queues and then one `redis-cli flushall` to clear redis cache.

**Comment by shirosaidev** [comment]
with less workers running are you still seeing this?

**Comment by mathse** [comment]
yep - it still like this

**Comment by shirosaidev** [comment]
the redis error or the es error?

**Comment by shirosaidev** [comment]
there are patches for this in rc28, let me know if this is fixed

**Comment by mathse** [comment]
fixed with commit https://github.com/shirosaidev/diskover/commit/5d0318503012c29c2881f2b18c581067e0694820#diff-c09f9ca8f2a3121b703e8245efd65e13
