### ISSUE TITLE
Missing ujson dependency

### ISSUE THREAD

**Issue by Itxaka** [shirosaidev/diskover#64]
v1.5.0-rc30 introduced the crawlapi which depends on ujson but the dependency was not added to the requirements.txt which causes diskover to fail to start:

```
2019-06-20 11:49:49,811 [INFO][diskover] Using config file: /app/diskover/diskover.cfg
Traceback (most recent call last):
  File "/app/diskover/diskover.py", line 2026, in <module>
    from diskover_socket_server import start_socket_server
  File "/app/diskover/diskover_socket_server.py", line 15, in <module>
    from diskover_bot_module import scrape_tree_meta
  File "/app/diskover/diskover_bot_module.py", line 39, in <module>
    from diskover_crawlapi import api_connection, api_stat
  File "/app/diskover/diskover_crawlapi.py", line 23, in <module>
    import ujson
ModuleNotFoundError: No module named 'ujson'
```

**Comment by shirosaidev** [comment]
fixed above and removed dependency for ujson in latest v1.5.0-rc30.

**Comment by Itxaka** [comment]
Thanks! This can be closed then!
