### ISSUE TITLE
KeyError: 'costpergb'

### ISSUE THREAD

**Issue by gerroon** [shirosaidev/diskover#75]
Hi

I am running the Linuxserver.io Docker  setup, everything seems to work but when I try to update the index using the json stuff in the admin panel this is the error I get when I click on the admin panel button again. And I do not see any reindex.

Not sure if I am using the wrong thing to reindex.

This is the json entry I use in the admin panel socket command.

`{"action": "reindex", "path": "/data/media, "recursive": "true"}`

constant.php

```
    // diskover.py socket listener server
    const ENABLE_SOCKET_CLIENT = true;
    const SOCKET_LISTENER_HOST = 'diskover';
    const SOCKET_LISTENER_PORT = 9999;

```

```
diskover         | Exception in thread Thread-3:
diskover         | Traceback (most recent call last):
diskover         |   File "/app/diskover/diskover_socket_server.py", line 371, in run_command
diskover         |     costpergb = str(command_dict['costpergb'])
diskover         | KeyError: 'costpergb'
diskover         | 
diskover         | During handling of the above exception, another exception occurred:
diskover         | 
diskover         | Traceback (most recent call last):
diskover         |   File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
diskover         |     self.run()
diskover         |   File "/usr/lib/python3.7/threading.py", line 870, in run
diskover         |     self._target(*self._args, **self._kwargs)
diskover         |   File "/app/diskover/diskover_socket_server.py", line 76, in socket_thread_handler
diskover         |     run_command(threadnum, command_dict, clientsock, cliargs, logger)
diskover         |   File "/app/diskover/diskover_socket_server.py", line 373, in run_command
diskover         |     costpergb = str(cliargs['costpergb'])
diskover         | KeyError: 'costpergb'
```

**Comment by shirosaidev** [comment]
This is a bug in the diskover-web, will fix in the next release. To reindex (recreate/update your index), you can console/terminal to the diskover docker container and run a normal diskover crawl using the how to on the diskover github readme.

**Comment by shirosaidev** [comment]
this bug has been fixed in latest update to file diskover_socket_server.py in master.
