### ISSUE TITLE
 [2017-05-09 13:03:50] [info] Found 30 duplicates  --Always Reports 30--

### ISSUE THREAD

**Issue by CopyRunStart** [shirosaidev/diskover#9]
I have run Diskover and then run it with the --dupesindex on four of my NFS mounts and all four report back "Found 30 Duplicates".  I think it's very unlikely that they all have exactly 30 duplicates so I'm thinking there might be a bug that is limiting it to 30.

Below are the results of indexing and dupes searching two different NFS mounts.

[2017-05-09 11:53:54] [status] Connecting to Elasticsearch
[2017-05-09 11:53:54] [info] Checking for ES index: diskover-2017.04.22
[2017-05-09 11:53:54] [warning] ES index exists, deleting
[2017-05-09 11:53:55] [info] Creating ES index
Crawling: [100%] |████████████████████████████████████████| 279718/279718
[2017-05-09 12:47:18] [status] Finished crawling
[2017-05-09 12:47:18] [info] Directories Crawled: 279718
[2017-05-09 12:47:18] [info] Files Indexed: 475561
[2017-05-09 12:47:18] [info] Elapsed time: 3204.14460206
python /diskover/diskover/diskover.py --dupesindex
[2017-05-09 13:03:49] [status] Connecting to Elasticsearch
[2017-05-09 13:03:49] [info] Checking for ES index: diskover_dupes-2017.04.22
[2017-05-09 13:03:49] [warning] ES index exists, deleting
[2017-05-09 13:03:49] [info] Creating ES index
[2017-05-09 13:03:50] [info] Found 30 duplicates
[2017-05-09 13:03:50] [status] Finished creating duplicate files index

[2017-05-08 20:08:21] [status] Connecting to Elasticsearch
[2017-05-08 20:08:21] [info] Checking for ES index: diskover-2017.04.22
[2017-05-08 20:08:21] [warning] ES index exists, deleting
[2017-05-08 20:08:21] [info] Creating ES index
Crawling: [100%] |████████████████████████████████████████| 70988/70988
[2017-05-08 20:50:11] [status] Finished crawling
[2017-05-08 20:50:11] [info] Directories Crawled: 70988
[2017-05-08 20:50:11] [info] Files Indexed: 3165862
[2017-05-08 20:50:11] [info] Elapsed time: 2510.63846493
python /diskover/diskover/diskover.py --dupesindex
[2017-05-09 09:46:18] [status] Connecting to Elasticsearch
[2017-05-09 09:46:19] [info] Checking for ES index: diskover_dupes-2017.04.22
[2017-05-09 09:46:19] [warning] ES index exists, deleting
[2017-05-09 09:46:19] [info] Creating ES index
[2017-05-09 09:46:19] [info] Found 30 duplicates
[2017-05-09 09:46:19] [status] Finished creating duplicate files index

**Comment by shirosaidev** [comment]
It seems like you are not using the cli argument --nodelete for the 2nd crawl:
`[2017-05-08 20:08:21] [warning] ES index exists, deleting`

Please take a look at the diagram on the README.md and you will see the CLI arguments and steps to use.

You need to run the --dupesindex after all the crawling/indexing is finished. You can run concurrent crawls/indexers but you need to use the --nodelete cli argument for additional crawls that you want to append/merge into an existing index.

**Comment by shirosaidev** [comment]
The diagram is under the heading **Speeding up crawl times**

**Comment by CopyRunStart** [comment]
Perhaps I'm misunderstanding but... doesn't that prove the bug?  I'm doing a completely new index each time I run.  I am not doing runs concurrently.  

To be specific, steps I took:

cd /mnt/NFS**1**/  
python /diskover/diskover/diskover.py -m 1 -s 1
\\Wait for it to Finish.
python /diskover/diskover/diskover.py --dupesindex
\\Results are 30 dupes from NFS1.

cd /mnt/NFS**2**/
python /diskover/diskover/diskover.py -m 1 -s 1
\\Wait for it to Finish.
python /diskover/diskover/diskover.py --dupesindex
\\Results are 30 **different** dupes from NFS2

And so on and so forth.

**Comment by shirosaidev** [comment]
Those two crawl will use an index name that is in the diskover.cfg file so you are overwriting the index on the 2nd crawl of NFS2. If you don't add the cli argument -i <index> it will use the index name in the config file.

**Comment by shirosaidev** [comment]
I've fixed this bug in **v1.0.8**, please download the new release and test again.

**Comment by CopyRunStart** [comment]
Seems fixed.  The first time running 1.0.8 --dupes I got the weird error below but after running a second time there was no issue.

`[2017-05-09 23:18:18] [status] Connecting to ElasticsearchTraceback (most recent call last):
  File "/diskover/diskover/diskover.py", line 533, in <module>
    main()
  File "/diskover/diskover/diskover.py", line 490, in main
    dupe_count = indexCreateDupes(ES, INDEXNAME, NODELETE, VERBOSE)
  File "/diskover/diskover/diskover.py", line 424, in indexCreateDupes
    dupes_list, dupe_count = dupesFinder(ES, INDEXNAME)
  File "/diskover/diskover/diskover.py", line 461, in dupesFinder
    res = ES.search(index=INDEXNAME, body=data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 625, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 122, in perform_request
    raise ConnectionTimeout('TIMEOUT', str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=10))
`

**Comment by shirosaidev** [comment]
I found a bug after testing more in v1.0.8 for duplicates, please download **v1.0.9** release from this morning and let me know how it goes.

**Comment by shirosaidev** [comment]
That error above looks like a http time out for Elasticsearch client communicating with the ES, maybe the server hosting ES was under too heavy load during that time or some other ES issue.

**Comment by CopyRunStart** [comment]
I'll try to test later tonight.  I had to spin down my Diskover VM to save memory on my ESXi host.  

Regarding my error after v1.0.8:  I agree, I don't think it was a Diskover error, just a Elasti error. 

Thanks again!
